config/routes.rb
OTD::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#home'
  get "home/home"
  get "home/about"
  
  scope :auth, :controller => :auth, :as => :auth do
    match 'sign_in', action: :login, via: [:get, :post]
    get 'sign_out', action: :sign_out
  end
  
  scope :home, :controller => :profiles, :as => :profile do
    get 'athlete_page'
    get 'trainer_page'
    match 'update_trainer', action: :update_trainer, via: [:get, :post]
    match 'update_athlete', action: :update_athlete, via: [:get, :post]
    match 'update_athlete_state', action: :update_athlete_state, via: [:get, :post]
  end
  
  scope :trainings, :controller => :trainings, :as => :trainings do
    match 'new_training', via: [:get, :post]
    match 'add_training', action: :add_training, via: [:get, :post]
    match 'training/:id', action: :show, via: [:get, :post]
    match 'remove_athlete', action: :remove_athlete, via: [:get, :post]
    match 'add_athlete', action: :add_athlete, via: [:get, :post]
    get 'fill_training/:id', action: :fill_training
    get 'trainings_history/:id', action: :trainings_history
    get 'trainer_trainings/:id', action: :trainer_trainings
  end
  
  scope :sections, :controller => :sections, :as => :sections do
    match 'add', action: :add, via: [:get, :post]
    match 'remove_section', action: 'remove_section', via: [:get, :post]
    match 'move_up', action: 'move_up', via: [:get, :post]
  end
  
  scope :groups, :controller => :groups, :as => :groups do
    match 'add_athlete', action: :add_athlete, via: [:get, :post]
  end
  
  scope :gathletes, :controller => :gathletes, :as => :gathletes do
    match 'add_athlete', action: :add_athlete, via: [:get, :post]
  end

  scope :athletes, :controller => :athletes, :as => :athletes do
    match 'new_athlete', action: :new_athlete, via: [:get, :post]
    match 'add_athlete', action: :add_athlete, via: [:get, :post]    
    match 'assign_athlete', action: :assign_athlete, via: [:get, :post]
    match 'athletes_list', action: :athletes_list, via: [:get, :post]
  end
  
  scope :atrainings, :controller => :atrainings, :as => :atrainings do
    match 'add_comment', action: :add_comment, via: [:get, :post]
  end
  
  scope :remote, :controller => :remote, :as => :remote do
    match 'get_trainings', action: :get_trainings, via: [:get, :post]
  end

  resources :trainers

  

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  require 'enumerator'
  require 'digest/md5'
  
  def athlete_page
    @athlete = current_user
    @trainer_trainings = Training.where(trainer_id: current_user.trainer.id).order('date DESC')
    @my_trainings = []
    @trainer_trainings.each do |t|
      if t.added(current_user)
        @my_trainings.append(t)
      end
    end
    @other_trainings = @trainer_trainings - @my_trainings
    @other_trainings = @other_trainings.take(5)
    @my_trainings = @my_trainings.take(5)
    @types = Athlete::PRIVACY_TYPES
  end
  
  def trainer_page
    @trainer = current_user
    @athletes = Athlete.where(trainer_id: current_user.id).order("surname asc")
    @trainings = Training.where(trainer_id: current_user.id).order('date DESC').first(5)    
  end
  
  def update_trainer
    #render json: params[:trainer]["birth(1i)"] + "-"+params[:trainer]["birth(2i)"]+"-"+params[:trainer]["birth(3i)"]
    @trainer = current_user
    @trainer.name = params[:trainer][:name]
    @trainer.surname = params[:trainer][:surname]
    @trainer.email = params[:trainer][:email]
    pass_changed = false
    @trainer.birth = params[:trainer]["birth(1i)"] + "-"+params[:trainer]["birth(2i)"]+"-"+params[:trainer]["birth(3i)"]
    
    if(params[:trainer][:password] == params[:trainer][:password_confirmation] && !params[:trainer][:password].blank?)
      @trainer.password = Digest::MD5.hexdigest(params[:trainer][:password])
      pass_changed = true
    end    
    
    if @trainer.changed?
      @trainer.save
      redirect_to root_path, notice: "Zmiany zostaly zapisane"
    else
      redirect_to root_path, notice: "Nie zapisano zadnych zmian"
    end
  end
  
  def update_athlete
    #render json: params
    @athlete = Athlete.find(params[:athlete][:id])
    @athlete.name = params[:athlete][:name]
    @athlete.surname = params[:athlete][:surname]
    @athlete.email = params[:athlete][:email]
    case params[:athlete][:privacy]
    when "Wszyscy"
      @athlete.privacy = 1
    when "Zarejestrowani"
      @athlete.privacy = 2
    when "Zawodnicy z grupy"
      @athlete.privacy = 3
    when "Tylko ja"
      @athlete.privacy = 4
    else
      @athlete.privacy = 4
    end
    
    pass_changed = false
    if params[:athlete]["birth(1i)"]
      @athlete.birth = params[:athlete]["birth(1i)"] + "-"+params[:athlete]["birth(2i)"]+"-"+params[:athlete]["birth(3i)"]
    end
    
    if(params[:athlete][:password] == params[:athlete][:password_confirmation] && !params[:athlete][:password].blank?)
      @athlete.password = Digest::MD5.hexdigest(params[:athlete][:password])
      pass_changed = true
    end    
    
    if @athlete.changed?
      @athlete.save
      redirect_to root_path, notice: "Zmiany zostaly zapisane"
    else
      redirect_to root_path, notice: "Nie zapisano zadnych zmian"
    end
  end
  
  def update_athlete_state    
    @athlete = Athlete.find(params[:athlete][:id])
    case params[:athlete][:state]
    when "Nie moze zakladac treningow"
      @athlete.state = 1
    when "Moze zakladac treningi"
      @athlete.state = 2
    else
      @athlete.state = 1
    end
    @athlete.save
    redirect_to :back
  end
  
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/athlete_page.html.erb
<div class = "wrapper content-training">
	<% @a = current_user %>
	<div class = "row margin-right-left trainer-page-content">
		<div class = "cent col-md-6">
			Ostatnie treningi: </br>
			<% @my_trainings.each do |t| %>
			<%= link_to t.date, :controller => "trainings", :action => "fill_training", :id => t.id, :a_id => @a.id %>
			<% if !t.participate(@a) %>
			Brak wpisów!
			<% end %>
			<br />
			<% end %>
			</br>
		</div>
		<div class = "cent col-md-6">
			Treningi trenera:</br>
			<% @other_trainings.each do |t| %>
			<%= t.date %> <%= link_to "Dołącz", :controller => "trainings", :action => "add_athlete", :id => t.id, :a_id => @a.id %></br>
			<% end %>
			</br>
			<%= link_to "Wszystkie", :controller => :trainings, :action => "trainer_trainings", :id => @a.trainer %> </br></br>
			<%= link_to 'Historia treningow', :controller => "trainings", :action => "trainings_history", :id => @a.id %>
		</div>
	</div>
	<div class = "row margin-right-left trainer-page-datas">

		<%= form_for @athlete, :url => url_for(:controller => "profiles", :action => "update_athlete"), method: :post do |f|%>
		<div id="data-edition" class="data-edition">
			<h3>Edytuj swoje dane</h3>
			<div class="form-group row">
				<%= f.label 'Imie', class: "col-xs-4 control-label to-right" %>
				<div class="col-xs-6">
					<%= f.text_field :name, class: "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<%= f.label 'Nazwisko', class: "col-xs-4 control-label to-right" %>
				<div class="col-xs-6">
					<%= f.text_field :surname, class: "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<%= f.label 'Email', class: "col-xs-4 control-label to-right" %>
				<div class="col-xs-6">
					<%= f.text_field :email, class: "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<%= f.label 'Haslo', class: "col-xs-4 control-label to-right" %>
				<div class="col-xs-6">
					<%= f.password_field :password, class: "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<%= f.label 'Potwierdz haslo', class: "col-xs-4 control-label to-right" %>
				<div class="col-xs-6">
					<%= f.password_field :password_confirmation, class: "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<%= f.label 'Pokaz historie moich treningow', class: "col-xs-4 control-label right" %>
				<div class="col-xs-8">
					<%= f.select :privacy, @types, :selected => @types[@athlete.privacy-1], class: "form-control " %>
				</div>
			</div>
			<div class="form-group row">
				<%= f.label 'Data urodzenia', class: "col-xs-4 control-label right" %>
				<div class="col-xs-6">
					<%= f.date_select :birth, start_year: 1900, class: "form-control" %>
				</div>
			</div>
			<div class = "row cent">
				<%= f.hidden_field :id, :value => current_user.id %>
			<%= f.submit "Zapisz zmiany", class: "btn btn-success"%>
			</div>

		</div>
		<% end %>
	</div>

</div>
</div>

app/views/profiles/trainer_page.html.erb
<div class = "wrapper content-training">
	<div class = "row margin-right-left trainer-page-content">
		<div class = "cent col-md-6">
			Moi zawodnicy: </br>
			<% @athletes.each do |a| %>
			<%= link_to a.full_name, :controller => :trainings, :action => "trainings_history", :id => a.id %> </br >
			<% end %>
			</br>
			<%= link_to "Dodaj zawodnika", athletes_add_athlete_path %>
		</div>
		<div class = "cent col-md-6">
			Ostatnie treningi:</br>
			<% @trainings.each do |t| %>
			<%= link_to t.date, trainings_path(t.id) %> </br>
			<% end %></br>
			<%= link_to "Wszystkie treningi", :controller => :trainings, :action => "trainer_trainings", :id => @trainer.id %>
			</br>
		</div>
	</div>
	<div class = "row margin-right-left trainer-page-datas">

		<%= form_for @trainer, :url => url_for(:controller => "profiles", :action => "update_trainer"), method: :post do |f|%>
		<div id="data-edition" class="data-edition">
			<h3>Edytuj swoje dane</h3>
			<div class="form-group row">
				<%= f.label 'Imie', class: "col-xs-4 control-label to-right" %>
				<div class="col-xs-6">
					<%= f.text_field :name, class: "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<%= f.label 'Nazwisko', class: "col-xs-4 control-label to-right" %>
				<div class="col-xs-6">
					<%= f.text_field :surname, class: "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<%= f.label 'Email', class: "col-xs-4 control-label to-right" %>
				<div class="col-xs-6">
					<%= f.text_field :email, class: "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<%= f.label 'Haslo', class: "col-xs-4 control-label to-right" %>
				<div class="col-xs-6">
					<%= f.password_field :password, class: "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<%= f.label 'Potwierdz haslo', class: "col-xs-4 control-label to-right" %>
				<div class="col-xs-6">
					<%= f.password_field :password_confirmation, class: "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<%= f.label 'Data urodzenia', class: "col-xs-4 control-label to-right" %>
				<div class="col-xs-6">
					<%= f.date_select :birth, start_year: 1900, class: "form-control" %>
				</div>
			</div>			
			<div class = "row cent">
				<%= f.submit "Zapisz zmiany", class: "btn btn-success"%>
			</div>
			</br>
		</div>
		<% end %>
	</div>

</div>