config/routes.rb
OTD::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#home'
  get "home/home"
  get "home/about"
  
  scope :auth, :controller => :auth, :as => :auth do
    match 'sign_in', action: :login, via: [:get, :post]
    get 'sign_out', action: :sign_out
  end
  
  scope :home, :controller => :profiles, :as => :profile do
    get 'athlete_page'
    get 'trainer_page'
    match 'update_trainer', action: :update_trainer, via: [:get, :post]
    match 'update_athlete', action: :update_athlete, via: [:get, :post]
    match 'update_athlete_state', action: :update_athlete_state, via: [:get, :post]
  end
  
  scope :trainings, :controller => :trainings, :as => :trainings do
    match 'new_training', via: [:get, :post]
    match 'add_training', action: :add_training, via: [:get, :post]
    match 'training/:id', action: :show, via: [:get, :post]
    match 'remove_athlete', action: :remove_athlete, via: [:get, :post]
    match 'add_athlete', action: :add_athlete, via: [:get, :post]
    get 'fill_training/:id', action: :fill_training
    get 'trainings_history/:id', action: :trainings_history
    get 'trainer_trainings/:id', action: :trainer_trainings
  end
  
  scope :sections, :controller => :sections, :as => :sections do
    match 'add', action: :add, via: [:get, :post]
    match 'remove_section', action: 'remove_section', via: [:get, :post]
    match 'move_up', action: 'move_up', via: [:get, :post]
  end
  
  scope :groups, :controller => :groups, :as => :groups do
    match 'add_athlete', action: :add_athlete, via: [:get, :post]
  end
  
  scope :gathletes, :controller => :gathletes, :as => :gathletes do
    match 'add_athlete', action: :add_athlete, via: [:get, :post]
  end

  scope :athletes, :controller => :athletes, :as => :athletes do
    match 'new_athlete', action: :new_athlete, via: [:get, :post]
    match 'add_athlete', action: :add_athlete, via: [:get, :post]    
    match 'assign_athlete', action: :assign_athlete, via: [:get, :post]
    match 'athletes_list', action: :athletes_list, via: [:get, :post]
  end
  
  scope :atrainings, :controller => :atrainings, :as => :atrainings do
    match 'add_comment', action: :add_comment, via: [:get, :post]
  end
  
  scope :remote, :controller => :remote, :as => :remote do
    match 'get_trainings', action: :get_trainings, via: [:get, :post]
  end

  resources :trainers

  

end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  require 'digest/md5'
  
  belongs_to :trainer
  has_many :trainings, :through => :atrainings
  has_many :atrainings
  has_many :sections, :through => :atrainings
  
  PRIVACY_TYPES = ["Wszyscy", "Zarejestrowani", "Zawodnicy z grupy", "Tylko ja"]
  STATE_TYPES = ["Nie moze zakladac treningow", "Moze zakladac treningi"]
  
  def sections_list (atid)
    Section.where(atraining_id: atid).order('sequence ASC')
  end
  
  def get_at (tid, aid)
    Atraining.where(training_id: tid).where(athlete_id: aid).first
  end
  
  def last_section_sequence (atid)
    sections_list(atid).size+1
  end
  
  def full_name
    name+ " "+surname
  end
  
  def get_trainings ()
    @trainings = trainings.order("date asc")
  end
  
  def authenticate (pass)
    self.password == Digest::MD5.hexdigest(pass)
  end
  
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  require 'digest/md5'
  
  
  def new_athlete
    @athlete = Athlete.new(athlete_params)
    @athlete.email = params[:athlete][:name][0, 2].downcase + params[:athlete][:surname][0, 3].downcase + "@gmail.com" if params[:athlete][:email].blank?
    #render json: athlete_params
    @athlete.privacy = 4
    pass = params[:athlete][:name][0, 2].downcase + params[:athlete][:surname][0, 3].downcase
    @athlete.password = Digest::MD5.hexdigest(pass)
    @athlete.state = 1
    @athlete.save
    redirect_to root_path, notice: "Dodano nowego zawodnika"
  end

  def add_athlete
    @athletes = Athlete.where("trainer_id is null")
  end
  
  def assign_athlete
    #render json: params
    @athlete = Athlete.find(params["athlete"]["athlete_id"])
    @athlete.trainer_id = current_user.id
    @athlete.save
    redirect_to root_path, notice: "Dodano nowego zawodnika"
  end
  
  def athletes_list
    @trainers = Trainer.all.order("surname asc")
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_athlete
      @athlete = Athlete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def athlete_params
      params.require(:athlete).permit(:name, :surname, :birth, :email, :password, :state, :privacy, :trainer_id)
    end
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/_form.html.erb
<%= form_for(@athlete) do |f| %>
  <% if @athlete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@athlete.errors.count, "error") %> prohibited this athlete from being saved:</h2>

      <ul>
      <% @athlete.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :birth %><br>
    <%= f.date_select(:birth, start_year: 1900) %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.number_field :state %>
  </div>
  <div class="field">
    <%= f.label :privacy %><br>
    <%= f.number_field :privacy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/athletes/add_athlete.html.erb
<div class = "wrapper content-training">
	<div class = "main-content">
		<% if @athletes.size > 0 %>
		<div class = "cent">
			Wybierz zawodnika z już zarejestrowanych:
			<%= form_for :athlete, :url => url_for(:controller => :athletes, :action => 'assign_athlete'), method: :post do |f| %>
			<div class="field">
				<br>
				<%= f.collection_select(:athlete_id, @athletes, "id", :full_name) %>
			</div>
			</br>
			<div class="actions">
				<% if can? :create, @athlete %>
				<%= f.hidden_field :trainer_id, :value => current_user.id %>
				<%= f.submit "Dodaj zawodnika", class: "btn btn-primary" %>
				<% end %>
			</div>
			<% end %>
		</div>
		<% end %>
		<div id = "new-athlete-box">
			<%= form_for :athlete, :url => url_for(:controller => :athletes, :action => 'new_athlete'), method: :post do |f| %>
			<div class="form-group row">
				<%= f.label 'Imie', class: "col-xs-4 control-label form-label" %>
				<div class="col-xs-6">
					<%= f.text_field :name, class: "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<%= f.label 'Nazwisko', class: "col-xs-4 control-label form-label" %>
				<div class="col-xs-6">
					<%= f.text_field :surname, class: "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<%= f.label 'Data urodzenia', class: "col-xs-4 control-label form-label" %>
				<div class="col-xs-6">
					<%= f.date_select :birth, start_year: 1900, class: "form-control" %>
				</div>
			</div>
			<div class="form-group row">
				<%= f.label 'Email', class: "col-xs-4 control-label form-label form-label" %>
				<div class="col-xs-6">
					<%= f.text_field :email, class: "form-control" %>
				</div>
			</div>
			<%= f.hidden_field :trainer_id, :value => current_user.id %>
			<div class="row cent">
				<%= f.submit "Dodaj zawodnika", class: "btn btn-primary" %>
			</div>
			</br>
			<% end %>
		</div>
		<!--<p class="slide">
			</br>
			<div class="pull-me btn-info">
				Kliknij, by dodać nowego!
			</div> 
		</p>-->
	</div>
</div>

app/views/athletes/athletes_list.html.erb
<div class = "wrapper content-training">
	<div class = "main-content">
		<div class = "row">
			<div class = "col-xs-offset-1 athlete-name">
				Lista zawodników:
			</div>
		</div>
		<% @trainers.each do |t| %>
			<div class = "row">
				<div class = "col-xs-offset-1 col-xs-11 trainer-name">
					<%= t.surname + " "+t.name %>
				</div>
				
					<% @athletes = t.athletes_list %>
					<% if @athletes.size > 0 %>
						<% @athletes.each do |a| %>
						<div class = "col-xs-offset-2 col-xs-10">	
							<div clas>
								<%= link_to a.full_name, :controller => "trainings", :action => "trainings_history", :id => a.id %>	
							</div>
							
						</div>
						<% end %>
					<% else %>
						<div class = "col-xs-offset-2 col-xs-10">	
							<div clas>
								Ten trener nie ma żadnych zawodników.	
							</div>
							
						</div>
					<% end %>
			</div>
		<% end %>
	</div>
</div>

app/views/athletes/edit.html.erb
<h1>Editing athlete</h1>

<%= render 'form' %>

<%= link_to 'Show', @athlete %> |
<%= link_to 'Back', athletes_path %>

app/views/athletes/index.html.erb
<h1>Listing athletes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Birth</th>
      <th>Email</th>
      <th>Password</th>
      <th>State</th>
      <th>Privacy</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @athletes.each do |athlete| %>
      <tr>
        <td><%= athlete.name %></td>
        <td><%= athlete.surname %></td>
        <td><%= athlete.birth %></td>
        <td><%= athlete.email %></td>
        <td><%= athlete.password %></td>
        <td><%= athlete.state %></td>
        <td><%= athlete.privacy %></td>
        <td><%= link_to 'Show', athlete %></td>
        <td><%= link_to 'Edit', edit_athlete_path(athlete) %></td>
        <td><%= link_to 'Destroy', athlete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Athlete', new_athlete_path %>

app/views/athletes/new.html.erb
<h1>New athlete</h1>

<%= render 'form' %>

<%= link_to 'Back', athletes_path %>

app/views/athletes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @athlete.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @athlete.surname %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @athlete.birth %>
</p>

<p>
  <strong>Email:</strong>
  <%= @athlete.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @athlete.password %>
</p>

<p>
  <strong>State:</strong>
  <%= @athlete.state %>
</p>

<p>
  <strong>Privacy:</strong>
  <%= @athlete.privacy %>
</p>

<%= link_to 'Edit', edit_athlete_path(@athlete) %> |
<%= link_to 'Back', athletes_path %>