config/routes.rb
OTD::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#home'
  get "home/home"
  get "home/about"
  
  scope :auth, :controller => :auth, :as => :auth do
    match 'sign_in', action: :login, via: [:get, :post]
    get 'sign_out', action: :sign_out
  end
  
  scope :home, :controller => :profiles, :as => :profile do
    get 'athlete_page'
    get 'trainer_page'
    match 'update_trainer', action: :update_trainer, via: [:get, :post]
    match 'update_athlete', action: :update_athlete, via: [:get, :post]
    match 'update_athlete_state', action: :update_athlete_state, via: [:get, :post]
  end
  
  scope :trainings, :controller => :trainings, :as => :trainings do
    match 'new_training', via: [:get, :post]
    match 'add_training', action: :add_training, via: [:get, :post]
    match 'training/:id', action: :show, via: [:get, :post]
    match 'remove_athlete', action: :remove_athlete, via: [:get, :post]
    match 'add_athlete', action: :add_athlete, via: [:get, :post]
    get 'fill_training/:id', action: :fill_training
    get 'trainings_history/:id', action: :trainings_history
    get 'trainer_trainings/:id', action: :trainer_trainings
  end
  
  scope :sections, :controller => :sections, :as => :sections do
    match 'add', action: :add, via: [:get, :post]
    match 'remove_section', action: 'remove_section', via: [:get, :post]
    match 'move_up', action: 'move_up', via: [:get, :post]
  end
  
  scope :groups, :controller => :groups, :as => :groups do
    match 'add_athlete', action: :add_athlete, via: [:get, :post]
  end
  
  scope :gathletes, :controller => :gathletes, :as => :gathletes do
    match 'add_athlete', action: :add_athlete, via: [:get, :post]
  end

  scope :athletes, :controller => :athletes, :as => :athletes do
    match 'new_athlete', action: :new_athlete, via: [:get, :post]
    match 'add_athlete', action: :add_athlete, via: [:get, :post]    
    match 'assign_athlete', action: :assign_athlete, via: [:get, :post]
    match 'athletes_list', action: :athletes_list, via: [:get, :post]
  end
  
  scope :atrainings, :controller => :atrainings, :as => :atrainings do
    match 'add_comment', action: :add_comment, via: [:get, :post]
  end
  
  scope :remote, :controller => :remote, :as => :remote do
    match 'get_trainings', action: :get_trainings, via: [:get, :post]
  end

  resources :trainers

  

end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :atraining
  has_many :trainings, :through => :atraining
  has_one :athlete, :through => :atraining
  
  def display_name
    length.to_s + " "+time.to_s
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def add
    @section = Section.new(section_params)
    @section.save
    redirect_to :back
  end
  
  def remove_section
    @section = Section.find(params[:id])
    @section.destroy
    redirect_to :back
  end
  
  def move_up
    @section = Section.find(params[:id])
    @seq = @section.sequence
    @sections = @section.atraining.sections
    @section2 = @sections.where(sequence: @seq-1).first()
    @section2.sequence = @seq
    @section2.save
    @section.sequence = @seq-1
    @section.save
    redirect_to :back
  end

  private

  def section_params
    params.require(:section).permit(:length, :time, :break, :sequence, :atraining_id)
  end

end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :training_id %><br>
    <%= f.collection_select :training_id, Training.order(:id), :id, :date, include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :length %><br>
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :break %><br>
    <%= f.text_field :break %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render 'form' %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<h1>Listing sections</h1>

<table>
  <thead>
    <tr>
      <th>Length</th>
      <th>Time</th>
      <th>Break</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.length %></td>
        <td><%= section.time %></td>
        <td><%= section.break %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New section</h1>

<%= render 'form' %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Length:</strong>
  <%= @section.length %>
</p>

<p>
  <strong>Time:</strong>
  <%= @section.time %>
</p>

<p>
  <strong>Break:</strong>
  <%= @section.break %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>