config/routes.rb
OTD::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#home'
  get "home/home"
  get "home/about"
  
  scope :auth, :controller => :auth, :as => :auth do
    match 'sign_in', action: :login, via: [:get, :post]
    get 'sign_out', action: :sign_out
  end
  
  scope :home, :controller => :profiles, :as => :profile do
    get 'athlete_page'
    get 'trainer_page'
    match 'update_trainer', action: :update_trainer, via: [:get, :post]
    match 'update_athlete', action: :update_athlete, via: [:get, :post]
    match 'update_athlete_state', action: :update_athlete_state, via: [:get, :post]
  end
  
  scope :trainings, :controller => :trainings, :as => :trainings do
    match 'new_training', via: [:get, :post]
    match 'add_training', action: :add_training, via: [:get, :post]
    match 'training/:id', action: :show, via: [:get, :post]
    match 'remove_athlete', action: :remove_athlete, via: [:get, :post]
    match 'add_athlete', action: :add_athlete, via: [:get, :post]
    get 'fill_training/:id', action: :fill_training
    get 'trainings_history/:id', action: :trainings_history
    get 'trainer_trainings/:id', action: :trainer_trainings
  end
  
  scope :sections, :controller => :sections, :as => :sections do
    match 'add', action: :add, via: [:get, :post]
    match 'remove_section', action: 'remove_section', via: [:get, :post]
    match 'move_up', action: 'move_up', via: [:get, :post]
  end
  
  scope :groups, :controller => :groups, :as => :groups do
    match 'add_athlete', action: :add_athlete, via: [:get, :post]
  end
  
  scope :gathletes, :controller => :gathletes, :as => :gathletes do
    match 'add_athlete', action: :add_athlete, via: [:get, :post]
  end

  scope :athletes, :controller => :athletes, :as => :athletes do
    match 'new_athlete', action: :new_athlete, via: [:get, :post]
    match 'add_athlete', action: :add_athlete, via: [:get, :post]    
    match 'assign_athlete', action: :assign_athlete, via: [:get, :post]
    match 'athletes_list', action: :athletes_list, via: [:get, :post]
  end
  
  scope :atrainings, :controller => :atrainings, :as => :atrainings do
    match 'add_comment', action: :add_comment, via: [:get, :post]
  end
  
  scope :remote, :controller => :remote, :as => :remote do
    match 'get_trainings', action: :get_trainings, via: [:get, :post]
  end

  resources :trainers

  

end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  require 'digest/md5'
  
  has_many :athletes
  has_many :trainings
  
  
  def display_name 
    name + " " + surname
  end
  
  def authenticate (pass)
    self.password == Digest::MD5.hexdigest(pass)
  end
  
  def athletes_list
    athletes.order("surname asc")
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trainer }
      else
        format.html { render action: 'new' }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:name, :surname, :birth, :email, :state)
    end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/_form.html.erb
<%= form_for(@trainer) do |f| %>
  <% if @trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
      <% @trainer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :birth %><br>
    <%= f.date_select :birth %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.number_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Editing trainer</h1>

<%= render 'form' %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<h1>Listing trainers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Birth</th>
      <th>Email</th>
      <th>State</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trainers.each do |trainer| %>
      <tr>
        <td><%= trainer.name %></td>
        <td><%= trainer.surname %></td>
        <td><%= trainer.birth %></td>
        <td><%= trainer.email %></td>
        <td><%= trainer.state %></td>
        <td><%= link_to 'Show', trainer %></td>
        <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trainer', new_trainer_path %>

app/views/trainers/new.html.erb
<h1>New trainer</h1>

<%= render 'form' %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trainer.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @trainer.surname %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @trainer.birth %>
</p>

<p>
  <strong>Email:</strong>
  <%= @trainer.email %>
</p>

<p>
  <strong>State:</strong>
  <%= @trainer.state %>
</p>

<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>